#!/usr/bin/env python3
#
# Using index generated by index_acs_calls.py, inserts comments before script
# lines documenting other scripts that start them.

import re
import sys

MAP_NAME_RE = re.compile(r"map(\d+)")
SCRIPT_RE = re.compile(r"script (\d+)")

scripts = {}

with open("calls_index.txt") as f:
    for line in f:
        parts = line.split(" ")
        filename, script = parts[0], int(parts[1])
        exmap, exscript = int(parts[2]), int(parts[3])
        scripts.setdefault((exmap, exscript), []).append((filename, script))

print(scripts)

for filename in sys.argv[1:]:
    mapnum = 0
    m = MAP_NAME_RE.match(filename)
    if not m:
        continue

    mapnum = int(m.group(1))

    lines = []
    with open(filename) as f:
        for line in f:
            line = line.rstrip()
            m = SCRIPT_RE.match(line)
            if m:
                script = int(m.group(1))
                for callmap, callscript in scripts.get((mapnum, script), []):
                    which_file = " in " + callmap if callmap != filename else ""
                    lines.append("// Started by script %d%s" % (callscript, which_file))
            lines.append(line)

    with open(filename, "w") as f:
        for line in lines:
            print(line, file=f)
